package com.example.pojo;
// Generated 5 sept. 2021 à 19:54:55 by Hibernate Tools 5.0.6.Final

/**
 * ActorInfo generated by hbm2java
 */
public class ActorInfo implements java.io.Serializable {

	private ActorInfoId id;

	public ActorInfo() {
	}

	public ActorInfo(ActorInfoId id) {
		this.id = id;
	}

	public ActorInfoId getId() {
		return this.id;
	}

	public void setId(ActorInfoId id) {
		this.id = id;
	}

}
