package com.example.pojo;
// Generated 5 sept. 2021 à 19:54:55 by Hibernate Tools 5.0.6.Final

/**
 * FilmList generated by hbm2java
 */
public class FilmList implements java.io.Serializable {

	private FilmListId id;

	public FilmList() {
	}

	public FilmList(FilmListId id) {
		this.id = id;
	}

	public FilmListId getId() {
		return this.id;
	}

	public void setId(FilmListId id) {
		this.id = id;
	}

}
