package com.example.pojo;
// Generated 5 sept. 2021 à 19:54:55 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventory generated by hbm2java
 */
public class Inventory implements java.io.Serializable {

	private int inventoryId;
	private Film film;
	private short storeId;
	private Date lastUpdate;
	private Set rentals = new HashSet(0);

	public Inventory() {
	}

	public Inventory(int inventoryId, Film film, short storeId, Date lastUpdate) {
		this.inventoryId = inventoryId;
		this.film = film;
		this.storeId = storeId;
		this.lastUpdate = lastUpdate;
	}

	public Inventory(int inventoryId, Film film, short storeId, Date lastUpdate, Set rentals) {
		this.inventoryId = inventoryId;
		this.film = film;
		this.storeId = storeId;
		this.lastUpdate = lastUpdate;
		this.rentals = rentals;
	}

	public int getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(int inventoryId) {
		this.inventoryId = inventoryId;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public short getStoreId() {
		return this.storeId;
	}

	public void setStoreId(short storeId) {
		this.storeId = storeId;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getRentals() {
		return this.rentals;
	}

	public void setRentals(Set rentals) {
		this.rentals = rentals;
	}

}
