package com.example.pojo;
// Generated 5 sept. 2021 à 19:54:55 by Hibernate Tools 5.0.6.Final

/**
 * NicerButSlowerFilmList generated by hbm2java
 */
public class NicerButSlowerFilmList implements java.io.Serializable {

	private NicerButSlowerFilmListId id;

	public NicerButSlowerFilmList() {
	}

	public NicerButSlowerFilmList(NicerButSlowerFilmListId id) {
		this.id = id;
	}

	public NicerButSlowerFilmListId getId() {
		return this.id;
	}

	public void setId(NicerButSlowerFilmListId id) {
		this.id = id;
	}

}
