package com.example.pojo;
// Generated 5 sept. 2021 à 19:54:55 by Hibernate Tools 5.0.6.Final

/**
 * SalesByStoreId generated by hbm2java
 */
public class SalesByStoreId implements java.io.Serializable {

	private String store;
	private String manager;
	private Byte totalSales;

	public SalesByStoreId() {
	}

	public SalesByStoreId(String store, String manager, Byte totalSales) {
		this.store = store;
		this.manager = manager;
		this.totalSales = totalSales;
	}

	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public Byte getTotalSales() {
		return this.totalSales;
	}

	public void setTotalSales(Byte totalSales) {
		this.totalSales = totalSales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalesByStoreId))
			return false;
		SalesByStoreId castOther = (SalesByStoreId) other;

		return ((this.getStore() == castOther.getStore()) || (this.getStore() != null && castOther.getStore() != null
				&& this.getStore().equals(castOther.getStore())))
				&& ((this.getManager() == castOther.getManager()) || (this.getManager() != null
						&& castOther.getManager() != null && this.getManager().equals(castOther.getManager())))
				&& ((this.getTotalSales() == castOther.getTotalSales())
						|| (this.getTotalSales() != null && castOther.getTotalSales() != null
								&& this.getTotalSales().equals(castOther.getTotalSales())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStore() == null ? 0 : this.getStore().hashCode());
		result = 37 * result + (getManager() == null ? 0 : this.getManager().hashCode());
		result = 37 * result + (getTotalSales() == null ? 0 : this.getTotalSales().hashCode());
		return result;
	}

}
